version: '3'

services:
  crawl-shell:
    image: crawl-shell
    restart: always

  crawl-python:
    image: crawl-python
    restart: always
    depends_on:
      - crawl-shell

  reverse-proxy:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - crawl-python